Controllers/ListingsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PinBackendSystem.Areas.Identity;
using PinBackendSystem.Data;
using PinBackendSystem.Models;
using PinBackendSystem.Services;
using PinBackendSystem.Util;


namespace PinBackendSystem.User.Controllers
{
    public class ListingsController : Controller
    {
        private readonly PinContext _context;
        private IConfiguration Configuration;
        private GeneralFunction _generalFunction;
        private UserManager<PinrumahUser> _userManager;
        BlobStorageService _blobStorageService;

        public ListingsController(PinContext context, IConfiguration _configuration, UserManager<PinrumahUser> userManager)
        {
            Configuration = _configuration;
            _context = context;
            _generalFunction = new GeneralFunction();
            _userManager = userManager;
            _blobStorageService = new BlobStorageService(Configuration.GetConnectionString("BlobStorageAccount"), Configuration.GetValue<string>("Azure:BlobContainerName"));
        }

        // GET: Listings
        public async Task<IActionResult> Index(string sortOrder, 
            string propertyType, string transactionType, string CurrentFilter, string searchString, 
            string minBed, string currentMinBed, string minPrice, string currentMinPrice,
            string maxPrice, string currentMaxPrice, string minLandSize, string currentMinLandSize,
            string maxLandSize, string currentMaxLandSize, string kota, string currentKota,
            string kecamatan, string currentKecamatan, int? pageNumber)
        {            

            int pageSize = 20;

            ViewBag.keywords = "Listing properti Indonesia";
            ViewBag.Description = "Listing rumah,apartemen,ruko,gedung dan tanah di Indonesia";


            ViewData["CurrentSort"] = sortOrder??string.Empty;
            ViewData["CurrentPropertyType"] = propertyType??string.Empty;
            ViewData["CurrentTransactionType"] = transactionType ?? string.Empty;

            // Use LINQ to get list of property type and others.
            IQueryable<string> propertyTypeQuery = from m in _context.Listings.OrderBy(s=>s.Id)
                                                   orderby m.PropertyType
                                                   select m.PropertyType;

            IQueryable<string> kotaQuery = from m in _context.Kotas.OrderBy(s => s.KotaName)
                                           select m.KotaName;

            IQueryable<string> kecamatanQuery = from m in _context.Kecamatans.OrderBy(s => s.Id)
                                                .Where(s => s.Kota.KotaName == kota)
                                                select m.KecamatanName;

            var listings = from m in _context.Listings
                           select m;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = CurrentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            if (minBed != null)
            {
                pageNumber = 1;
            }
            else
            {
                minBed = currentMinBed;
            }

            ViewData["CurrentMinBed"] = minBed;

            if (minPrice != null)
            {
                pageNumber = 1;
            }
            else
            {
                minPrice = currentMinPrice;
            }

            ViewData["CurrentMinPrice"] = minPrice;

            if (maxPrice != null)
            {
                pageNumber = 1;
            }
            else
            {
                maxPrice = currentMaxPrice;
            }

            ViewData["CurrentMaxPrice"] = maxPrice;

            if (minLandSize != null)
            {
                pageNumber = 1;
            }
            else
            {
                minLandSize = currentMinLandSize;
            }

            ViewData["CurrentMinLandSize"] = minLandSize;

            if (maxLandSize != null)
            {
                pageNumber = 1;
            }
            else
            {
                maxLandSize = currentMaxLandSize;
            }

            ViewData["CurrentMaxLandSize"] = maxLandSize;

            if (kota != null)
            {
                pageNumber = 1;
            }
            else
            {
                kota = currentKota;
            }

            ViewData["currentKota"] = kota;

            if (kecamatan != null)
            {
                pageNumber = 1;
            }
            else
            {
                kecamatan = currentKecamatan;
            }

            ViewData["currentKecamatan"] = kecamatan;

            if (!string.IsNullOrEmpty(searchString))
            {
                listings = listings.Where(s => EF.Functions.Like(s.Title.ToUpper(), $"%{searchString.ToUpper()}%"));
            }

            if (!string.IsNullOrEmpty(minBed))
            {
                int noOfMinBed;
                int.TryParse(minBed, out noOfMinBed);
                listings = listings.Where(s => s.NoOfBed >= noOfMinBed);
            }

            if (!string.IsNullOrEmpty(minPrice))
            {
                decimal noOfMinPrice;
                Decimal.TryParse(minPrice, out noOfMinPrice);
                listings = listings.Where(s => s.Price >= noOfMinPrice);
            }

            if (!string.IsNullOrEmpty(maxPrice))
            {
                decimal noOfMaxPrice;
                Decimal.TryParse(maxPrice, out noOfMaxPrice);
                listings = listings.Where(s => s.Price <= noOfMaxPrice);
            }

            if (!string.IsNullOrEmpty(minLandSize))
            {
                decimal noOfMinLandSize;
                Decimal.TryParse(minLandSize, out noOfMinLandSize);
                listings = listings.Where(s => s.LandSize >= noOfMinLandSize);
            }

            if (!string.IsNullOrEmpty(maxLandSize))
            {
                decimal noOfMaxLandSize;
                Decimal.TryParse(maxLandSize, out noOfMaxLandSize);
                listings = listings.Where(s => s.LandSize <= noOfMaxLandSize);
            }

            if (!string.IsNullOrEmpty(propertyType))
            {
                listings = listings.Where(x => x.PropertyType == propertyType);
            }

            if (!string.IsNullOrEmpty(transactionType))
            {
                listings = listings.Where(x => x.TransactionType == transactionType);
            }

            if (!string.IsNullOrEmpty(kota))
            {
                listings = listings.Where(x => x.Kota == kota);
            }

            if (!string.IsNullOrEmpty(kecamatan))
            {
                listings = listings.Where(x => x.Kecamatan == kecamatan);
            }

            //show only published listing
            listings = listings.Where(x => x.Status == PinrumahConstants.AdsStatus);

            

            switch (sortOrder)
            {
                case "date_desc":
                    listings = listings.OrderByDescending(s => s.CreatedOn);
                    break;
                case "price_asc":
                    listings = listings.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    listings = listings.OrderByDescending(s => s.Price);
                    break;
                case "rating_asc":
                    listings = listings.OrderBy(s => s.Rating);
                    break;
                case "rating_desc":
                    listings = listings.OrderByDescending(s => s.Rating);
                    break;
                default:
                    listings = listings.OrderByDescending(s => s.CreatedOn);
                    break;
            }

            var listingPropertyTypeVM = new ListingPropertyTypeViewModel
            {
                PropertyType = new SelectList(await propertyTypeQuery.Where(s=>!string.IsNullOrEmpty(s)).Distinct().ToListAsync()),
                Kota = new SelectList(await kotaQuery.Where(s => !string.IsNullOrEmpty(s)).ToListAsync()),
                Kecamatan = new SelectList(await kecamatanQuery.Where(s => !string.IsNullOrEmpty(s)).ToListAsync()),
                Listings = await PaginatedList<Listing>.CreateAsync(listings.AsNoTracking(), pageNumber ?? 1, pageSize)
            };
            return View(listingPropertyTypeVM);
            // return View(await _context.Listing.ToListAsync());
        }

        public async Task<IActionResult> Home(string sortOrder,
            string propertyType, string transactionType, string CurrentFilter, string searchString,
            string minBed, string currentMinBed, string minPrice, string currentMinPrice,
            string maxPrice, string currentMaxPrice, string minLandSize, string currentMinLandSize,
            string maxLandSize, string currentMaxLandSize, string kota, string currentKota,
            string kecamatan, string currentKecamatan,
            int? pageNumber)
        {

            int pageSize = 20;

            ViewBag.keywords = "Listing properti Indonesia";
            ViewBag.Description = "Listing rumah,apartemen,ruko,gedung dan tanah di Indonesia";


            ViewData["CurrentSort"] = sortOrder ?? string.Empty;
            ViewData["CurrentPropertyType"] = propertyType ?? string.Empty;
            ViewData["CurrentTransactionType"] = transactionType ?? string.Empty;

            // Use LINQ to get list of genres.
            IQueryable<string> propertyTypeQuery = from m in _context.Listings.OrderBy(s => s.Id)

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines

@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pinrumah</title>
    <link rel="stylesheet" href="~/Identity/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Identity/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light navbar-toggleable-sm bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="~/">Pinrumah</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @{
                        var result = Engine.FindView(ViewContext, "_LoginPartial", isMainPage: false);
                    }
                    @if (result.Success)
                    {
                        await Html.RenderPartialAsync("_LoginPartial");
                    }
                    else
                    {
                        throw new InvalidOperationException("The default Identity UI layout requires a partial view '_LoginPartial' " +
                            "usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration " +
                            $"we have looked at it in the following locations: {System.Environment.NewLine}{string.Join(System.Environment.NewLine, result.SearchedLocations)}.");
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer border-top text-muted">
    </footer>
    <script src="~/Identity/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Identity/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Identity/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_User_Layout.cshtml
@{
    Uri url = new Uri(String.Format("{0}://{1}{2}{3}", Context.Request.Scheme, Context.Request.Host, Context.Request.Path, Context.Request.QueryString));
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pinrumah</title>
    <meta name="keywords" content="@ViewBag.Keywords" />
    <meta name="Descption" content="@ViewBag.Description" />
    <meta property="og:title" content="@ViewData["Title"]" />
    <meta property="og:url" content="@url" />
    <meta property="og:description" content="@ViewBag.Description">
    <meta property="og:image" content="@ViewBag.Image">


    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link href="~/theme/plugins/fontawesome-free/css/all.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/theme/dist/css/adminlte.min.css">
    <!-- pinrumah own css-->
    <link rel="stylesheet" href="~/theme/dist/css/pinrumah-main.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css" />
</head>
<body class="skin-blue layout-top-nav">
    <!-- Site wrapper -->
    <div class="wrapper ">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light _hide-in-mobile">
            <div class="container">
                <!-- Left navbar links -->
                <ul class="navbar-nav">
                    <li class="nav-item d-sm-inline-block">
                        <a asp-controller="Listings" asp-action="Home" class="nav-link text-pinrumah-color">Home</a>
                    </li>
                    <li class="nav-item d-sm-inline-block">
                        <a asp-controller="Home" asp-action="Contact" class="nav-link text-pinrumah-color">Contact</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item d-sm-inline-block">
                            <a asp-controller="Listings" asp-area="Admin" asp-action="Personal" class="nav-link">Admin Page</a>
                        </li>
                    }
                </ul>
                <div class="_branding-image-index"><img class="branding__image" alt="Pinrumah" width="170" height="47" src="~/theme/dist/img/logopinrumah.png"></div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
        <!-- /.navbar -->
        <!--Navbar-->
        <nav class="navbar navbar-light light-blue lighten-4 _hide-in-desktop">

            <!-- Collapse button -->
            <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1"
                    aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="dark-blue-text">
                    <i class="fas fa-bars fa-1x"></i>
                </span>
            </button>

            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent1">

                <!-- Links -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item d-sm-inline-block">
                        <a asp-controller="Listings" asp-action="Index" class="nav-link text-pinrumah-color">Home</a>
                    </li>
                    <li class="nav-item d-sm-inline-block">
                        <a asp-controller="Home" asp-action="Contact" class="nav-link text-pinrumah-color">Contact</a>
                    </li>
                </ul>

                <!-- Links -->
                <partial name="_LoginPartial" />
            </div>

            <!-- Collapsible content -->

        </nav>
        <!--/.Navbar-->

        @RenderBody()
    <a href="https://api.whatsapp.com/send?phone=6281280069222&text=Halo%21%20Saya%20mau%20tanya%20soal%20rumah%20nih" class="_wa-float" target="_blank">
        <i class="fa fa-whatsapp _wa-my-float"></i>
    </a>
    <footer class="main-footer" style="background-color: #F5F5F5;clear:both;">
        
        <div class="text-center">
            <a href="#"><img width="30" src="~/theme/dist/img/fb.png"></a>
            <a href="#"><img width="30" src="~/theme/dist/img/ig.png"></a>
            <a href="#"><img width="30" src="~/theme/dist/img/youtube.png"></a>
        </div>
        <div>
            <nav class="navbar navbar-expand navbar-light">
                <div>
                    <!-- Left navbar links -->
                    <ul class="navbar-nav _desktop-float-left" style="padding-bottom:3%;white-space: nowrap;">
                        <li class="nav-item d-sm-inline-block">
                            <a asp-controller="Listings" asp-action="Home" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item d-sm-inline-block">
                            <a asp-controller="Home" asp-action="Contact" class="nav-link">Contact</a>
                        </li>
                        <li class="nav-item d-sm-inline-block">
                            <a asp-controller="Home" asp-action="Contact" class="nav-link">Privacy Policy</a>
                        </li>
                        
                    </ul>
                    <ul class="navbar-nav _desktop-float-right">
                        <li class="nav-item d-sm-inline-block">
                            <a asp-controller="Home" asp-action="Contact" class="nav-link">Help Centre</a>
                        </li>
                        <li class="nav-item d-sm-inline-block">
                            <a asp-controller="Home" asp-action="Contact" class="nav-link">Media</a>
                        </li>
                        <li class="nav-item d-sm-inline-block">
                            <a asp-controller="Home" asp-action="Contact" class="nav-link">Legal</a>
                        </li>
                        <li class="nav-item d-sm-inline-block">
                            <a asp-controller="Home" asp-action="Contact" class="nav-link">Career</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div style="padding:1%;">
            <strong>Copyright &copy; 2020 Pinrumah.com.</strong> All rights
            reserved.
        </div>
    </footer>

    </div>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    <!-- Bootstrap 4 -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <!-- AdminLTE App -->
    <script src="~/theme/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/theme/dist/js/demo.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.18/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.18/dist/js/bootstrap-select.min.js"></script>

    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>